# Generated by Django 4.0.2 on 2022-03-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('region', models.CharField(max_length=50)),
                ('link_img', models.CharField(max_length=1024)),
                ('departamento', models.CharField(max_length=500)),
            ],
        ),
    ]
